

  CUSTOM_HAL_IMGSENSOR = ov2680_mipi_raw hi545_mipi_raw 
 CUSTOM_KERNEL_IMGSENSOR = hi545_mipi_raw ov2680_mipi_raw

	  CUSTOM_HAL_LENS    = fm50af dummy_lens    

CUSTOM_HAL_FLASHLIGHT = dummy_flashlight
CUSTOM_HAL_MAIN_IMGSENSOR = hi546_mipi_raw 
CUSTOM_KERNEL_MAIN_IMGSENSOR = hi545_mipi_raw
CUSTOM_KERNEL_SUB_IMGSENSOR = ov2680_mipi_raw
CUSTOM_HAL_SUB_IMGSENSOR = ov2680_mipi_raw
